# Generated by Django 3.2.3 on 2021-09-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idmascota', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo_mascota', models.IntegerField(max_length=11)),
                ('propietario', models.IntegerField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('idpropietario', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=60)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_mascota',
            fields=[
                ('idtipo_mascota', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
    ]
