# Generated by Django 3.2.3 on 2021-09-22 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mascota',
            table='mascota',
        ),
        migrations.AlterModelTable(
            name='propietario',
            table='propietario',
        ),
        migrations.AlterModelTable(
            name='tipo_mascota',
            table='tipo_mascota',
        ),
    ]
