# Generated by Django 3.2.3 on 2021-09-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210921_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='idmascota',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.propietario'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipo_mascota'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='idpropietario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_mascota',
            name='idtipo_mascota',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
