# Generated by Django 3.2.3 on 2021-09-22 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210921_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(blank=True, db_column='propietario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.propietario'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.ForeignKey(db_column='tipo_mascota', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipo_mascota'),
        ),
    ]
